### ISSUE TITLE
Setting to specify what fleet to leave behind when Moon-jumping

### ISSUE THREAD

**Issue by christiankm** [ogame-infinity/web-extension#10]
<img width="367" alt="Skærmbillede 2021-01-05 kl  21 15 15" src="https://user-images.githubusercontent.com/3626094/103694330-1bcee080-4f9b-11eb-9621-845855c4539a.png">
https://discord.com/channels/735582742435201114/735584342830612540/783292996098457629

**Comment by alexisfasquel** [comment]
Is it not already the case ? 
I thought I took care of this, but I don't really remember and have no way of testing atm...

**Comment by rteuwens** [comment]
Discord Response to this user's request: [[link](https://discord.com/channels/735582742435201114/735584342830612540/786913246090625045)]

Infinity's settings are global (apply to moon and planet)
![image](https://user-images.githubusercontent.com/30375696/103703640-33609600-4fa8-11eb-9bf5-4d80876a45af.png)
![image](https://user-images.githubusercontent.com/30375696/103703652-38bde080-4fa8-11eb-9aa1-8bb48f5c71d2.png)


This should be closed imo.

**Comment by Bishop341-B** [comment]
Since version 2.3.2, in addition to the global keep resources & ships setting, the local per planet (or moon) should we working ok. It opens in fleet1 page, in the fleet dispatcher.

![imagen](https://user-images.githubusercontent.com/13818551/236786904-b032508a-00ab-4ea6-8376-2cf282242197.png)
