### ISSUE TITLE
Track items collected from Expeditions

### ISSUE THREAD

**Issue by christiankm** [ogame-infinity/web-extension#11]
<img width="372" alt="Skærmbillede 2021-01-05 kl  21 15 52" src="https://user-images.githubusercontent.com/3626094/103694393-31440a80-4f9b-11eb-8e6f-09fe76643494.png">
https://discord.com/channels/735582742435201114/735584342830612540/784009678191329280

**Comment by alexisfasquel** [comment]
None of them are collected ? 
As anyone been able to test that ? 
e.g it was supposed to work on at least french server and I'm surprised it would not work on others...

**Comment by rteuwens** [comment]
Can confirm.

![image](https://user-images.githubusercontent.com/30375696/103752402-fd53fe00-5009-11eb-91f1-6469b0b9f93f.png)

Gold Deut booster found.
Marked as "Nothing".
Not appearing in stats.

![image](https://user-images.githubusercontent.com/30375696/103752492-1197fb00-500a-11eb-8621-7cc893b78b88.png)

**Comment by alexisfasquel** [comment]
Alright, thanks !

**Comment by blag001** [comment]
solved
