### ISSUE TITLE
Resource-icons in Overview are "shifted" (on Microsoft Edge)

### ISSUE THREAD

**Issue by christiankm** [ogame-infinity/web-extension#14]
<img width="378" alt="Skærmbillede 2021-01-05 kl  21 21 46" src="https://user-images.githubusercontent.com/3626094/103694930-04dcbe00-4f9c-11eb-9f93-e5814a78e535.png">
<img width="309" alt="Skærmbillede 2021-01-05 kl  21 21 53" src="https://user-images.githubusercontent.com/3626094/103694939-08704500-4f9c-11eb-958f-acfe1b44710a.png">
https://discord.com/channels/735582742435201114/735582967564468237/786298848577847306

**Comment by alexisfasquel** [comment]
Is it only edge ? 
I though I had seen the issue also on chrome ?

**Comment by christiankm** [comment]
It might be all Windows, i have only seen it on Edge on Windows. Not in Chrome on Mac.

Christian

**Comment by alexisfasquel** [comment]
@christiankm I had the issue on my mac just before testing @tritens's PR
