### ISSUE TITLE
Update Expedition Translations: Polish

### ISSUE THREAD

**Issue by christiankm** [ogame-infinity/web-extension#16]
<img width="375" alt="Skærmbillede 2021-01-05 kl  21 29 01" src="https://user-images.githubusercontent.com/3626094/103695516-08247980-4f9d-11eb-94c2-5851e60313fc.png">
https://discord.com/channels/735582742435201114/735583479252910130/779311059000361001

**Comment by Bishop341-B** [comment]
Various expedition message updates were made after this was opened.
