### ISSUE TITLE
Update Expedition Messages: Turkish

### ISSUE THREAD

**Issue by christiankm** [ogame-infinity/web-extension#17]
<img width="590" alt="Skærmbillede 2021-01-05 kl  21 29 32" src="https://user-images.githubusercontent.com/3626094/103695558-1a061c80-4f9d-11eb-9cb6-7957a7debc8c.png">

**Comment by christiankm** [comment]
<img width="607" alt="Skærmbillede 2021-01-05 kl  21 30 32" src="https://user-images.githubusercontent.com/3626094/103695630-3e61f900-4f9d-11eb-8ee2-6624cbd3348b.png">
https://discord.com/channels/735582742435201114/735583479252910130/789296491721916416

**Comment by Bishop341-B** [comment]
Various expedition message updates were made after this was opened.
