### ISSUE TITLE
Update Expedition Messages: Polish

### ISSUE THREAD

**Issue by christiankm** [ogame-infinity/web-extension#18]
<img width="616" alt="Skærmbillede 2021-01-05 kl  21 31 25" src="https://user-images.githubusercontent.com/3626094/103695689-5df92180-4f9d-11eb-90a7-19fe7d14e321.png">
<img width="626" alt="Skærmbillede 2021-01-05 kl  21 31 35" src="https://user-images.githubusercontent.com/3626094/103695706-63ef0280-4f9d-11eb-9067-61290d396421.png">
https://discord.com/channels/735582742435201114/735583479252910130/795971322475053076

**Comment by Bishop341-B** [comment]
Various expedition message updates were made after this was opened.
