### ISSUE TITLE
Automatic empire auto fetch causes left menu to change planet

### ISSUE THREAD

**Issue by Gloorf** [ogame-infinity/web-extension#181]
I'm having this issue a lot in master, not in 2.3.2, and it's because of LF scraping (I think).

Steps to reproduce :

1. Go on planet A
2. Wait for automatic empire fetch to start (look at the "infinite loading sign" on the right menu)
3. Open your network tab to see requests to URL like this `https://s191-fr.ogame.gameforge.com/game/index.php?page=ingame&component=bonussettings&cp=[a planet id, but not the one you're on]`
4. Click on the "fleet" button on the left menu to go to the fleet page of planet A (this works with any page)
5. Instead of changing to the fleet page of planet A, you'll instead get to fleet page of planet B, depending on whichever planet was loaded last by the background auto fetch

If you wait for the auto fetch to end (or disable auto fetch), you won't have any issue - because the planet you're currently on is loaded last.

I'm not sure how to fix this, but IMO the best way is to edit the links on the left menu to always contain the `cp=` part : this way you'll always end up on the correct planet. But I'm not sure what's the exact policy around extension is, and if you're allowed to do that (modify the existing menu).

**Comment by Bishop341-B** [comment]
Fixed with #185
