### ISSUE TITLE
The code crashes on black hole messages

### ISSUE THREAD

**Issue by Warsaalk** [ogame-infinity/web-extension#2]
It seems like the script crashes on black hole message as shown in the screenshot below.
This also prevents the script from registering expedition message on the next pages.

![image](https://user-images.githubusercontent.com/2462755/90291162-99c10c80-de7f-11ea-9fb6-fd884593ab43.png)

**Comment by alexisfasquel** [comment]
Thanks @Warsaalk! 
Closing (I thing the changes in the tsv fixed it correcty :)
