### ISSUE TITLE
Moon Facility: Resource Lock not functional & level toggle unavailable

### ISSUE THREAD

**Issue by rteuwens** [ogame-infinity/web-extension#20]
![image](https://user-images.githubusercontent.com/30375696/103704376-7b33ed00-4fa9-11eb-8bb8-44f044029193.png)
![image](https://user-images.githubusercontent.com/30375696/103704521-bcc49800-4fa9-11eb-995c-fbd9d59762ad.png)

Clicking the lock does not result in the familiar red lock next to the planet.
Can also not toggle building levels.

Bug is not due to moon being fully built. This is what it should look like:
![image](https://user-images.githubusercontent.com/30375696/103704445-9d2d6f80-4fa9-11eb-8570-2409e82053e7.png)

**Comment by tritens** [comment]
Should be fixed by #29
