### ISSUE TITLE
Adding players to block list links to lobby (fr) 

### ISSUE THREAD

**Issue by rteuwens** [ogame-infinity/web-extension#21]
![image](https://user-images.githubusercontent.com/30375696/103716885-6153d380-4fc4-11eb-989d-953696332042.png)

Clicking the button highlighted in orange (block player) leads to `https://lobby.ogame.gameforge.com/fr_FR/hub` .
It does not destroy the session (can go back and keep playing).

Perhaps an incomplete feature that was postponed and forgotten.

**Comment by MatHoffman** [comment]
resolved by commit #35
