### ISSUE TITLE
Update Expedition Translations: Portuguese (Portugal)

### ISSUE THREAD

**Issue by F1S1C0** [ogame-infinity/web-extension#31]
Portuguese - nothing found

1.
De: Comando da frota
A tua frota entrou no campo gravitacional de uma estrela de neutrões. Para conseguir escapar à enorme força da gravidade teve de gastar grande parte do Deutério e cancelar a expedição.

2. 
De: Comando da frota
Um virus de computador atacou o sistema de navegação mesmo antes da frota sair do nosso sistema solar. O virus fez com que a frota andasse a voar em círculo. Não deverá ser necessário dizer que a missão falhou.

https://cdn.discordapp.com/attachments/735583479252910130/796690766474641418/unknown.png

3. 

De: Comando da frota
Bem, agora sabemos que aquelas anomalias vermelhas de classe 5 para além de ter efeitos caóticos nos sistemas de navegação também são altamente alucinogénos.

https://cdn.discordapp.com/attachments/735583479252910130/796690945092747284/unknown.png

**Comment by PlumbLeech** [comment]
I have a google sheet for pt-PT. https://docs.google.com/spreadsheets/d/11Z208OT2vLTuhRGQzt1_I6Jv_13RAoSgVW69JYpu5Tw/edit?usp=sharing

**Comment by Bishop341-B** [comment]
Various expedition message updates were made after this was opened.
