### ISSUE TITLE
Bugs after ogame's server migration

### ISSUE THREAD

**Issue by sfabruz** [ogame-infinity/web-extension#325]
Hi.
In Italy, last week, ogame did a migration of some servers to another one, the “s254-it” Yin.
It's a bit strange all the bugs I have, first of all the extension doesn't save “data management” correctly, although it doesn't throw any error. 
All the names within the high score are “undefined” and, of course, all their planets are invisible. That is, in the tooltip that appears when I hover over a player's name with the mouse, only one or two planets are visible. Sometimes even zero and it is not possible.
The general statistics are always zero for all categories, and searching for players does not always return results.
I have tried different browsers and different pcs, but the problems are always there.
It seems that the problem is related to the server.
I have tried clearing all the cache, local and session memory, uninstalling and reinstalling the extension, but all the problems are still there.
All the problems started when the server was migrated. When I was on Xuange (s253-it) the extension was working fine.
What should I do to get the extension working again?

**Comment by Bishop341-B** [comment]
That is more a limitation of the use of Ogame API data to build all that lists and info, than a bug. Ogame API data is updated by GF at different rates, some data is updated once a day or even worse, once a week.

https://forum.origin.ogame.gameforge.com/forum/thread/44-ogame-api/

When there is a new server some ogame API is not available form the first moment until that updates rates. May be it happens the same when servers get joined. Please, just try to wait 1 week to get all that data updated and in sync with ogame servers.

**Comment by sfabruz** [comment]
Thanks for your reply.
It's working, a few hours ago it started working properly.
Thanks again, I close the issue.
