### ISSUE TITLE
[Bug] Cargo amount resets to 0

### ISSUE THREAD

**Issue by peti446** [ogame-infinity/web-extension#358]
Hi,

When using the extension, when I try to send any cargo, it works fine, but if the number goes to the 1000 it always resets back to 0, If i try to set the max using the yellow buttons, it does not work either it will reset to 0. 

If I do not use the extensions it works fine, I wonder if maybe it has to do with . vs , ? I think the original version uses , but the extension tries to use . ?

**Comment by blag001** [comment]
You changed the language.
We don't support the use of a language other than the server's one. 
Separator are not the same and will break hover 1k units. 

Try to get back to the server default configuration, it should solve itself.

**Comment by peti446** [comment]
That did it thanks, yep separatos are different.
