### ISSUE TITLE
Resources Images in Stats are displaced

### ISSUE THREAD

**Issue by F1S1C0** [ogame-infinity/web-extension#36]
Small issue

The resource icons (Crystal and Deuterium) appear displaced too far to the left.

![](https://cdn.discordapp.com/attachments/770598621364224070/798570976173490176/unknown.png)

![](https://cdn.discordapp.com/attachments/770598621364224070/798570899552862238/unknown.png)

**Comment by rteuwens** [comment]
This was fixed.

https://github.com/ogame-infinity/web-extension/pull/24

**Comment by F1S1C0** [comment]
Duplicate with #24
