### ISSUE TITLE
New setting for type of/number of ships to send for expeditions as standard

### ISSUE THREAD

**Issue by christiankm** [ogame-infinity/web-extension#9]
When sending expedition from the fleet screen, we can click the button to profile probe, reaper, cargos, etc. But (for me) it always only adds 417 Large Cargo, and usually I would want to send 2000 or 4000. Let's add some settings to specify exactly what and how many ships that button actually selects.

**Comment by F1S1C0** [comment]
We need to be careful so Gameforge accepts this plugin.

When we have activated Commander, one of the benefits it's to have a feature called "Standard fleets" where you can set up which ships you want to send.
As so, if Infinity mimics this behavior we take the risk of being ban or illegal to use it.

What can be done is something like OGLigth to set up a ratio between 2 ships of your choice.

**Comment by emilianosalatino** [comment]
where in the code is the number of cargo ships for expeditions defined? I can't find it. I've noticed it updates to a larger number as the universe evolves.
