### ISSUE TITLE
Cannot write more than 3 carachters in the fleet tab for resources and ships.

### ISSUE THREAD

**Issue by duncan53** [ogame-infinity/web-extension#92]
Only on version 2.0.17 and 2.0.18

In the fleet tab when I write a number over 3 digits everything is erased to leave only the first digit.

**Comment by xTaak** [comment]
Same for me ... i switched to OGLight and no bug :D just activity tracking it's better on Ogame Infinity, but for the rest OGLight is better ;)

**Comment by LonestarX91** [comment]
it will be fixed in the next version, very soon

**Comment by duncan53** [comment]
It dont work in 2.0.19 ?

**Comment by Yorik87** [comment]
Same for me, on TW server. How can i solve?

**Comment by duncan53** [comment]
In 2.0.10 its ok just update your extension

**Comment by Yorik87** [comment]
> In 2.0.10 its ok just update your extension

On TW server doesn’t work
I have 2.0.20
